name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

# Grant GITHUB_TOKEN the permissions required to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify translations
        run: dart run tool/verify_translations.dart

      - name: Activate Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: Build
        run: dart pub global run jaspr_cli:jaspr build --dart-define JASPR_BASE=/coinky/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/jaspr'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
